### PR TITLE
It seems to be working now

### PR DESCRIPTION
**Pull request by sbago**

### CODE REVIEW

**Comment by Exorion1er** [comment]
Just tried to run dungeon 1 of DT running this build, which it did record, but when trying to play it in an inn it says "Unable to play. Data does not exist". Haven't tried others yet.

**Comment by Exorion1er** [comment]
Couple issues :
- Scanning with cursor through the list of recordings, anything not underneath or above cursor disappears
- Scrubbing through a recording breaks everything and crashes my game. Logs don't seem to mention anything about it tho.

**Comment by sbago** [comment]
> Couple issues :
> 
> * Scanning with cursor through the list of recordings, anything not underneath or above cursor disappears
> * Scrubbing through a recording breaks everything and crashes my game. Logs don't seem to mention anything about it tho.

it seem fixed in lastest commit

**Comment by IllidraEthorn** [comment]
Not sure if I'm doing something wrong here, but I've built the code in this PR and recording will not start in any duties.

**Comment by sbago** [comment]
> Not sure if I'm doing something wrong here, but I've built the code in this PR and recording will not start in any duties.
Check if there are any automatically named replay files in your folder. cid check has not been fully patched, and the game cannot load replay files it recognizes. Some brothers believe that reply files without automatic naming should not appear in the List on the right, so filtered them out.
I am trying to follow up on this issue

**Comment by sbago** [comment]
> Not sure if I'm doing something wrong here, but I've built the code in this PR and recording will not start in any duties.

Check if there are any automatically named replay files in your folder. cid check has not been fully patched, and the game cannot load replay files it recognizes. Some brothers believe that reply files without automatic naming should not appear in the List on the right, so filtered them out.
I am trying to follow up on this issue

**Comment by sbago** [comment]
> > Not sure if I'm doing something wrong here, but I've built the code in this PR and recording will not start in any duties.
> 
> Check if there are any automatically named replay files in your folder. cid check has not been fully patched, and the game cannot load replay files it recognizes. Some brothers believe that reply files without automatic naming should not appear in the List on the right, so filtered them out. I am trying to follow up on this issue

now can record

**Comment by kaedys** [comment]
Piping in to say I'm running a local build of this as well, and it is also working, after I deleted the automatic named ones under `\Documents\My Games\FINAL FANTASY XIV - A Realm Reborn\replay`.

**Pull request closed without merging**
